version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - "9000:9000"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net

  db_host: 
    container_name: db
    image: mysql:5.7
    envirnoment: 
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
        - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
networks:
  net:
  
  

